# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bed344b8a21c406286fe80df8bfe8e7e3f697ae886e8e49e7765bfcd67a4b80ccbdbe4387ca307edebff73d9d85aac043c44e0731a0a1906e30f3be92d6f7bd5

test:
  secret_key_base: 09607311cbd6ee7f3511b4ae343fc464ae3523092b5ae9e137c653d81dbc157e135d9e6193fbef655b21c504e3753111491be8b92189a1f103b3c334bfc31ce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
